version: 2.1
executors:
  cypress-latest:
    docker:
      - image: "cypress/base:latest" # Replace with the latest Node.js version available
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          executor: cypress-latest
          install-command: "yarn install --frozen-lockfile"
          build: "yarn build"
      - cypress/run:
          executor: cypress-latest
          requires:
            - cypress/install
          record: false
          parallel: true
          parallelism: 4
          group: "all tests"
          start: "yarn start:cypress"
          post-steps:
            - run: yarn test
