export const users = [
	{
		pk: 1,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		twitterLink: 'https://twitter.com/UnitapNFT',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		pk: 2,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		twitterLink: 'https://twitter.com/UnitapNFT',
	},
	{
		pk: 3,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		twitterLink: 'https://twitter.com/UnitapNFT',
	},
	{
		pk: 4,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		pk: 5,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		pk: 6,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		pk: 7,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		pk: 8,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		pk: 9,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		pk: 10,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
]