export const users = [
	{
		id: 1,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@User',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		twitterLink: 'https://twitter.com/UnitapNFT',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		id: 2,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		twitterLink: 'https://twitter.com/UnitapNFT',
	},
	{
		id: 3,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@NewUsername',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.040',
		twitterLink: 'https://twitter.com/UnitapNFT',
	},
	{
		id: 4,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: 'Test',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.00004',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		id: 5,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username A',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		id: 6,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username AB',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		id: 7,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		id: 8,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		id: 9,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		id: 10,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		id: 11,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		twitterLink: 'https://twitter.com/UnitapNFT',
	},
	{
		id: 12,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		id: 13,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 14,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		id: 14,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		id: 15,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		id: 16,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		id: 17,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		id: 18,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
	{
		id: 19,
		image: 'assets/images/leaderboard/profileImage.svg',
		userName: '@Username',
		level: 13,
		walletAddress: '0x22377..2939',
		totalGas: '5,039.04',
		instagramLink: 'https://discord.com/invite/UnitapNFT',
	},
]